### ISSUE TITLE
No indent on PDF body

### ISSUE THREAD

**Issue by lucaspatel** [jseanpatel/Maribel#16]
The body of the PDF does not have an indent.

**Comment by jseanpatel** [comment]
It is supposed to lack any indentation. The user is to add their own indentation where they see fit. I do not believe it would make sense to add a default indentation at the beginning of the PDF and then let the user figure out their own for each subsequent indent.

**Comment by lucaspatel** [comment]
Why not just check for indent if there is some and then display it properly either way ? It is not intuitive the current way - Nick found it confusing.
